box::use(
  shiny.fluent[Pivot, PivotItem],
  shiny[div, moduleServer, tags],
)

# Defining pivot (tab panel) with concepts to understand training
# inputs. Content is generated by rendered quarto documents in logic.
#' @export
ui <- function(id) {

  div(
    style = "padding: 0 28px 28px 28px; background-color: white;",
    class = "ms-depth-8",
    Pivot(
      PivotItem(
        headerText = "Transformations",
        tags$iframe(
          src = "static/transformations.html",
          width = "100%%",
          height = "450px",
          frameBorder = "0"
        )
      ),
      PivotItem(
        headerText = "Training vectors",
        tags$iframe(
          src = "static/training_vectors.html",
          width = "100%",
          height = "450px",
          frameBorder = "0"
        )
      ),
      PivotItem(
        headerText = "LSTM",
        tags$iframe(
          src = "static/lstm.html",
          width = "100%",
          height = "450px",
          frameBorder = "0"
        )
      ),
      PivotItem(
        headerText = "Training & Testing",
        tags$iframe(
          src = "static/training_test.html",
          width = "100%",
          height = "450px",
          frameBorder = "0"
        )
      )
    )
  )
}

#' @export
server <- function(id) {
  moduleServer(id, function(input, output, session) {

  })
}
